resources:
  repositories:
    - repository: templates
      type: github
      name: Tereius/conan-azure-templates
      endpoint: Tereius

jobs:
- job: Android
  strategy:
    matrix:
      armv7Linux:
        imageName: "ubuntu-16.04"
        buildProfile: "androidArmv7LinuxHost"
      armv7Windows:
        imageName: "windows-2019"
        buildProfile: "androidArmv7WinHost"
  pool:
    vmImage: '$(imageName)'
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_PATH: "./buildProfiles/$(buildProfile).profile",
        CONAN_BUILD_PROFILE: "default",
      }

- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "Release",
        CONAN_BASE_PROFILE_OS: "Linux",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Linux",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "gcc",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "5",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libstdc++"
      }

- job: Windows
  pool:
    vmImage: "vs2017-win2016"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "Release",
        CONAN_BASE_PROFILE_OS: "Windows",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Windows",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "Visual Studio",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "15"
      }
      
- job: Macos
  pool:
    vmImage: "macOS-10.14"
  timeoutInMinutes: 0
  steps:
  - template: buildConanRecipe.yml@templates
    parameters:
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_REMOTES: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_BASE_PROFILE_BUILDTYPE: "Release",
        CONAN_BASE_PROFILE_OS: "Macos",
        CONAN_BASE_PROFILE_OS_VERSION: "10.14",
        CONAN_BASE_PROFILE_ARCH: "x86_64",
        CONAN_BASE_PROFILE_OSBUILD: "Macos",
        CONAN_BASE_PROFILE_ARCHBUILD: "x86_64",
        CONAN_BASE_PROFILE_COMPILER: "apple-clang",
        CONAN_BASE_PROFILE_COMPILER_VERSION: "10.0",
        CONAN_BASE_PROFILE_COMPILER_LIBCXX: "libc++"
      }
    
- job: Upload
  dependsOn:
  - Android
  - Linux
  - Windows
  - Macos
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - template: uploadConanRecipe.yml@templates
    parameters: 
      conanEnv: {
        CONAN_USERNAME: "tereius",
        CONAN_CHANNEL: "stable",
        CONAN_UPLOAD: "https://conan.privatehive.de/artifactory/api/conan/public-conan",
        CONAN_LOGIN_USERNAME: "ci",
        CONAN_PASSWORD: "$(secret)",
      }
